name: python-application

on: pull_request

jobs:
    linting:
        runs-on: ubuntu-latest
        steps:
            # checking out the source code from repository using actions/checkoutv3
            - name: Check out repo source code
              uses: actions/checkout@v3
            - name: Set up python
              id: setup-python
              uses: actions/setup-python@v4
              with:
                python-version: "3.10"
            # Setting up poetry to install dependencies to run the job
            - name: Install poetry
              uses: snok/install-poetry@v1
              with:
                virtualenvs-create: true
                virtualenvs-in-project: true
                installer-parallel: true
            # Load cached venv if cache exists
            - name: Load cached venv
              id: cached-poetry-dependencies
              uses: actions/cache@v3
              with:
                path: .venv
                key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
            # Install dependencies if cache does not exist
            - name: Install Dependencies
              if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
              run: poetry install --no-interaction --no-root
              # Tests
            - name: Run tests
              run: |
                source .venv/bin/activate
                flake8 app/
                black app/ --check
